### ISSUE TITLE
Model textures not supported

### ISSUE THREAD

**Issue by mdudek** [yermolim/ts-basic-gltf-viewer#1]
Hi @yermolim, your viewer looks great, but i have found that glb model textures are not rendered. Is it possible to update viewer to support it?

**Comment by yermolim** [comment]
> Hi @yermolim, your viewer looks great, but i have found that glb model textures are not rendered. Is it possible to update viewer to support it?

Hi @mdudek. This viewer was originally intended for dealing with large industrial building models. The main goal was to make it possible to open dozens of models with thousands of elements and millions of polygons while keeping an optimal render performance. Optimized mesh merging to reduce render calls, GPU picking, using only vertex colors, etc. were the ways to achieve it. And textures were out of scope. But I doubt it'd be easy to implement textures support while keeping current optimizations. I'll keep this open for now. If there will be more requests or I'll have some free time, I'll see what I can do.

**Comment by yermolim** [comment]
I'm closing this for now.
