### ISSUE TITLE
IFC.js integration

### ISSUE THREAD

**Issue by agviegas** [yermolim/ts-basic-gltf-viewer#2]
Hola!

This project is really cool. We are struggling with optimization in IFC.js, and in the future this kind of experiments might be very useful. Just checking in to say hello and let you know that if you ever want to integrate this with IFC.js ecosystem, build other things with IFC.js or just [chat](https://discord.gg/FXfyR4XrKT), you can count on us. 😉

Sorry for opening the issue, but we didn't know how to contact you. 

Cheers!

**Comment by yermolim** [comment]
Hi, @agviegas! 
Thanks for your feedback, I appreciate it 🙏. And thanks for your offer, I'll keep it in mind.  I would be happy to contact you if I need your advice on the further development of this project or on the future ones. And also thanks for your project, which made it possible to load IFC files into this one.
And I also added some contact information to my profile, so feel free to let me know if you need my help (I doubt I can be really useful to you, but who knows). 
👋
